### ISSUE TITLE
I cannot run graphql-cop

### ISSUE THREAD

**Issue by Riskmatrix0897** [dolevf/graphql-cop#25]
Every time I run the command python3 graphql-cop -t {target IP} i get this output.  I am not sure what to do please advise.

Traceback (most recent call last):
  File "/home/hapihacker/tools/graphql-cop/graphql-cop.py", line 101, in <module>
    json_output.append(test(path, proxy, HEADERS, options.debug_mode))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hapihacker/tools/graphql-cop/lib/tests/dos_field_duplication.py", line 22, in field_duplication
    res['curl_verify'] = curlify(gql_response)
                         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hapihacker/tools/graphql-cop/lib/utils.py", line 9, in curlify
    req = obj.request
          ^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'request'

**Comment by dolevf** [comment]
please reopen this ticket if you have more information to provide.
